stages:
  - build
  - test
  - tag
  - deploy

variables:
  IMAGE_NAME: "registry.service.wetopi.priv/vote-ab-server"

build image:
  stage: build
  only:
    - tags

  script:
    - echo "Build image $IMAGE_NAME:$CI_COMMIT_SHORT_SHA to $IMAGE_NAME:$CI_COMMIT_TAG"
    - docker build --pull -t "$IMAGE_NAME:$CI_COMMIT_SHA" .
    - docker push "$IMAGE_NAME:$CI_COMMIT_SHA"


tag:
  stage: tag
  environment:
    name: production
    url: https://vote-ab-server.wpviva.com/

  script:
    - docker pull "$IMAGE_NAME:$CI_COMMIT_SHA"

    - echo "Tag image $IMAGE_NAME:$CI_COMMIT_SHA to $IMAGE_NAME:$CI_COMMIT_TAG"
    - docker tag "$IMAGE_NAME:$CI_COMMIT_SHA" "$IMAGE_NAME:$CI_COMMIT_TAG"
    - docker push "$IMAGE_NAME:$CI_COMMIT_TAG"

    - echo "Tag image $IMAGE_NAME:$CI_COMMIT_SHA to $IMAGE_NAME:latest"
    - docker tag "$IMAGE_NAME:$CI_COMMIT_SHA" "$IMAGE_NAME:latest"
    - docker push "$IMAGE_NAME:latest"

  only:
    - tags



update play:
  image: registry.service.wetopi.priv/docker-ansible:$WETOPI_CI_DOCKER_VERSION
  stage: deploy
  environment:
    name: playground
    url: http://app-api-play.service.wetopi.priv:8082/api/

  script:
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@git.wetopi.net/wetopi/app-runner.git
    - cd app-runner
    - echo "service update playground $IMAGE_NAME:$CI_COMMIT_TAG ====>"
    - ansible-playbook -e env=playground -e name_suffix="-play" -e make=update -e image_version="$CI_COMMIT_TAG" app-api.yml
  when: manual
  only:
    - tags


create play:
  image: registry.service.wetopi.priv/docker-ansible:$WETOPI_CI_DOCKER_VERSION
  stage: deploy
  environment:
    name: playground
    url: http://app-api-play.service.wetopi.priv:8082/api/

  script:
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@git.wetopi.net/wetopi/app-runner.git
    - cd app-runner
    - echo "service create playground $IMAGE_NAME:$CI_COMMIT_TAG ====>"
    - ansible-playbook -e env=playground -e name_suffix="-play" -e make=create -e image_version="$CI_COMMIT_TAG" app-api.yml
  when: manual
  only:
    - tags


remove play:
  image: registry.service.wetopi.priv/docker-ansible:$WETOPI_CI_DOCKER_VERSION
  stage: deploy
  environment:
    name: playground
    url: http://app-api-play.service.wetopi.priv:8082/api/

  script:
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@git.wetopi.net/wetopi/app-runner.git
    - cd app-runner
    - echo "service remove playground ====>"
    - ansible-playbook -e env=playground -e name_suffix="-play" -e make=remove app-api.yml
  when: manual
  only:
    - tags

update prod:
  image: registry.service.wetopi.priv/docker-ansible:$WETOPI_CI_DOCKER_VERSION
  stage: deploy
  environment:
    name: production
    url: https://app-api.wetopi.com/v1/

  script:
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@git.wetopi.net/wetopi/app-runner.git
    - cd app-runner
    - echo "service update production $IMAGE_NAME:$CI_COMMIT_TAG ====>"
    - ansible-playbook -e env=production -e name_suffix="" -e make=update -e image_version="$CI_COMMIT_TAG" app-api.yml
  when: manual
  only:
    - tags

create prod:
  image: registry.service.wetopi.priv/docker-ansible:$WETOPI_CI_DOCKER_VERSION
  stage: deploy
  environment:
    name: production
    url: https://app-api.wetopi.com/v1/

  script:
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@git.wetopi.net/wetopi/app-runner.git
    - cd app-runner
    - echo "service update create $IMAGE_NAME:$CI_COMMIT_TAG ====>"
    - ansible-playbook -e env=production -e name_suffix="" -e make=create -e image_version="$CI_COMMIT_TAG" app-api.yml
  when: manual
  only:
    - tags

remove prod:
  image: registry.service.wetopi.priv/docker-ansible:$WETOPI_CI_DOCKER_VERSION
  stage: deploy
  environment:
    name: production
    url: https://app-api.wetopi.com/v1/

  script:
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@git.wetopi.net/wetopi/app-runner.git
    - cd app-runner
    - echo "service remove production ====>"
    - ansible-playbook -e env=production -e name_suffix="" -e make=remove app-api.yml
  when: manual
  only:
    - tags
